dist: bionic
language: python

env:
- MONGODB_VERSION=3.4
- MONGODB_VERSION=3.6
- MONGODB_VERSION=4.0
python:
- 3.6
- &latest_py3 3.8

cache: pip

install:
- pip install tox tox-venv

before_script:
  - mkdir mongodb
  - wget http://downloads.mongodb.org/linux/mongodb-linux-x86_64-v$MONGODB_VERSION-latest.tgz -q -O - | tar xz -C mongodb --strip-components=1
  - export PATH=$(pwd)/mongodb/bin:$PATH
  # Enable IPv6. Ref travis-ci/travis-ci#8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi

script:
- tox
- export PATH=$(pwd)/.tox/python/bin:$PATH
- which mongo
- mongo --nodb tests/oplog.js
